import { HashMap } from "./hashmap.js"
import { HashSet } from "./hashset.js"
let test = new HashMap()
test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

console.log(test.keys())
console.log("=================================================================================================")
let rat = new HashSet()
rat.set('apple')
rat.set('banana')
rat.set('carrot')
rat.set('dog')
rat.set('elephant')
rat.set('frog')
rat.set('grape')
rat.set('hat')
rat.set('ice cream')
rat.set('jacket')
rat.set('kite')
rat.set('lion')
// console.log(rat.remove("grape"))
console.log(rat.get("dog"))
console.log(rat.length())
console.log(rat.keys())
